### ISSUE TITLE
Particle converges on point on trajectory, why?

### ISSUE THREAD

**Issue by huetufemchopf** [nkdnnlr/Event-Based-Camera-Simultaneous-Mosaicing-and-Tracking#7]
<img width="621" alt="Bildschirmfoto 2019-05-03 um 17 41 06" src="https://user-images.githubusercontent.com/24462913/57149332-c0168200-6dcb-11e9-8035-5b39680db069.png">
<img width="390" alt="Bildschirmfoto 2019-05-03 um 17 40 23" src="https://user-images.githubusercontent.com/24462913/57149333-c0168200-6dcb-11e9-98ad-abd3524cbeeb.png">

**Comment by nkdnnlr** [comment]
We estimated the three sigmas for the update step according to the rotation seen from the ground truth poses. For a batch size of 300, the resulting sigmas are 
sigma_x = 3.366398763318423e-05
sigma_y = 3.366410184326084e-05
sigma_z = 0.0005285784750737629

Because there seems to be not much movement if those are used, we use different multiplier on the sigmas. Below a zoomed in image of the output of 1000001 events, with multiplier 200. See log file below for more details.
![output_f200](https://user-images.githubusercontent.com/23656702/57178824-c6156d00-6e76-11e9-8e0e-27b1dd391f4c.png)

There is not really movement happening either, also convergence on the yellow point. Trying different sigmas, but probably something else goes wrong. 

[quaternions_04052019T063735.log](https://github.com/nkdnnlr/Event-Based-Camera-Simultaneous-Mosaicing-and-Tracking/files/3144330/quaternions_04052019T063735.log)
